name: "Horusec"
description: "Secure Code Analysis."

inputs:
  # github-token:
  #   required: true
  #   default: ${{ github.token }}
  horusec-version:
    required: false
    default: "v2.8.0"
  project-path:
    required: false
    type: string
    default: "."
  ignore:
    required: false
    type: string
    default: null
  config-file-path:
    required: false
    type: string
    default: null

runs:
  using: 'node16'
  main: 'dist/index.js'