name: "Horusec"
description: "Secure Code Analysis."

inputs:
  horusec_version:
    required: false
    default: "v2.8.0"
  project_path:
    required: false
    type: string
    default: "."
  ignore:
    required: false
    type: string
    default: null
  config_file_path:
    required: false
    type: string
    default: null

runs:
  using: 'node16'
  main: 'dist/index.js'