name: Horusec Action

on:
  pull_request: [ 'main' ]

jobs:
  Horusec:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Execute
        continue-on-error: true
        uses: ./
        with:
          github-token: ${{github.token}}
          use-summary: true
          enable-commit-author: true

